version: '3'

services:
  math-server:
    build: ./server
    container_name: math-server
    networks:
      - local_default
    ports:
      - "8081:80"
    volumes:
      - ./server:/go/src/github.com/schigh/cposc2017_app/server

  math-client:
    build: ./client
    container_name: math-client
    networks:
      - local_default
    ports:
      - "8082:80"
    volumes:
      - ./client:/go/src/github.com/schigh/cposc2017_app/client
    depends_on:
      - math-server

networks:
  local_default:
    external: true

